language: php
php:
- 5.5
- 5.4
- hhvm
before_script: phpenv config-add files/php/fpm/php.ini
services:
  - mongodb
script: phpunit www/src/DembeloMain/Tests/Controller/DefaultControllerTest.php
install:
- composer --working-dir="www" install