language: php
php:
- 5.5
- 5.4
- hhvm
before_script:
- pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
services:
  - mongodb
script: phpunit www/src/DembeloMain/Tests/Controller/DefaultControllerTest.php
install:
- composer --working-dir="www" install