language: php
php:
- 7
- 5.6
- 5.5
before_install:
- echo "extension =" $MONGOEXTENSION >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
services:
  - mongodb
script:
- phpcs --config-set installed_paths www/vendor/escapestudios/symfony2-coding-standard
- phpcs --standard=symfony2 www/src
- phpunit -c www/app/
install:
- IF [ "$MONGOEXTENSION" = "mongo.so" ] THEN composer remove "alcaeus/mongo-php-adapter"; fi
- composer --working-dir="www" install
- pyrus install pear/PHP_CodeSniffer
- phpenv rehash
matrix:
  allow_failures:
    - php: 7
  include:
    - php: 5.5
      env: MONGOEXTENSION="mongo.so"
    - php: 5.6
      env: MONGOEXTENSION="mongo.so"
    - php: 7
      env: MONGOEXTENSION="mongodb.so"