language: php
php:
- 5.6
- 7
before_install:
- echo "extension =" $MONGOEXTENSION >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
services:
  - mongodb
script:
- ./www/bin/phpcs --config-set installed_paths www/vendor/escapestudios/symfony2-coding-standard
- ./www/bin/phpcs --standard=symfony2 www/src
- ls -l www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php
- ./www/bin/phpunit -c www/app/
install:
- if [[ $MONGOEXTENSION == "mongo.so" ]]; then composer --working-dir="www" remove alcaeus/mongo-php-adapter mongodb/mongodb; fi
- composer --working-dir="www" install
- phpenv rehash
matrix:
  include:
    - php: 5.6
      env: MONGOEXTENSION="mongo.so"
    - php: 7
      env: MONGOEXTENSION="mongodb.so"