data_management_domain:
    resource: "@DataManagementDomainBundle/"
    prefix:   /

app:
    resource: "@DembeloMain/Controller/"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

logout:
    path: /logout