# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: DembeloMain\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.dashboard_controller:
        class: DembeloMain\Controller\Dashboard\DefaultController
        arguments: ["@templating","@app.textNode_repository"]

    app.textNode_repository:
        class: DembeloMain\Model\Repository\Doctrine\ODM\TextNodeRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\Textnode